name: checkout
description: checkout and do some other things
inputs:
  ssh-private-key:
    description: SSH private key
    required: false

  fetch-depth:
    description: git checkout fetch-depth
    type: number
    required: false
    default: 0

  ls_options:
    description: ls options
    required: false
    # in windows, la does NOT work
    default: "-la"

runs:
  using: composite
  steps:
    - uses: webfactory/ssh-agent@v0.9.0
      if: ${{ inputs.ssh-private-key != '' }}
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: ls
      shell: bash
      run: ls ${{ inputs.ls_options }}
