name: checkout
description: checkout and do some other things
inputs:
  ssh-private-key:
    description: SSH private key
    required: false

  repository:
    description: Repository to check out
    required: false
    default: ${{ github.repository }}

  path:
    description: Relative path under $GITHUB_WORKSPACE to place the repository
    required: false
    default: ""

  submodules:
    description: whether to update submodules
    required: false
    default: "false"

  fetch-depth:
    description: git checkout fetch-depth
    required: false
    default: "0"

  ls_options:
    description: ls options
    required: false
    # in windows, la does NOT work
    default: "-la"

runs:
  using: composite
  steps:
    # FIXME?: checkout seems to fully support ssh-key
    - uses: webfactory/ssh-agent@v0.9.0
      if: ${{ inputs.ssh-private-key != '' }}
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    # SRC: https://github.com/actions/checkout
    - name: checkout
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        fetch-depth: ${{ inputs.fetch-depth }}
        path: ${{ inputs.path }}

    - name: git submodule update
      if: ${{ inputs.submodules == 'true' }}
      shell: bash
      run: |
        git submodule update --init --recursive
        git submodule update --remote

    - name: ls
      shell: bash
      run: ls ${{ inputs.ls_options }}
