name: ssh-agent
description: Configure SSH
inputs:
  ssh-private-key:
    description: SSH private key
    required: false

runs:
  using: composite
  steps:
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}
