name: ssh-agent
description: Configure SSH
inputs:
  ssh-private-key:
    description: SSH private key
    required: true

runs:
  using: composite
  steps:
    # SRC: https://github.com/webfactory/ssh-agent
    - uses: webfactory/ssh-agent@v0.10.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}
