name: actions/checkout
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  ls_options:
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        ls_options:
          - "-la"
          - "-l"
          - "-a"
        OS:
          - ubuntu-latest
          - macos-latest
        include:
          - OS: windows-latest
            ls_options: ""

    runs-on: ${{ matrix.os }}
    name: checkout ls ${{ matrix.ls_options }} @ ${{ matrix.OS }}
    steps:
      # FIXME: maybe checkout conflicts with the 'checkout' action
      # - uses: ./.github/actions/checkout # FIXME
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        with:
          ls_options: ${{ matrix.ls_options }}
