name: "[C]ontinuous [I]ntegration"
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

env:
  # auto-select LTS version
  NODE_VERSION: ""

jobs:
  lint:
    name: npm run lint
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main

      # NOTE: We could use github-actions-node
      # But it has a dependency on github-actions-common
      - name: setup node @ ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      # NOTE: We could use github-actions-npm
      # But it has a dependency on github-actions-common
      - name: npm run setup:ci
        run: npm run setup:ci --if-present

      - name: npm install
        run: npm ci
      - name: ls node_modules
        run: ls -la ./node_modules

      - name: npm run lint
        run: npm run lint

  codeQL:
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language:
          - actions

    name: "CodeQL: ${{ matrix.language }}"
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        with:
          ssh-private-key: ${{ secrets.SSH_KEY_PRIVATE }}

      - name: setup CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: CodeQL
        uses: github/codeql-action/analyze@v3
