name: dependency-review

# "This run was triggered by the "push" event, which is unsupported.
#  Please ensure you are using the "pull_request" event for this workflow."
on:
  pull_request:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows

permissions:
  contents: read

inputs:
  ssh-private-key:
    required: false
    default: ""

  submodules:
    type: boolean
    required: false
    default: false

jobs:
  dependency-review:
    name: dependency-review
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        with:
          ssh-private-key: ${{ inputs.ssh-private-key }}
          submodules: ${{ inputs.submodules }}

      - name: dependency-review
        uses: actions/dependency-review-action@v2
