name: Test actions/artifact-*
on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  default:
    runs-on: ubuntu-latest
    name: default
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/artifact-upload

      - name: rm ./dist
        run: rm -rf ./dist

      - uses: ./.github/actions/artifact-download

  path__matrix:
    needs: default
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        path:
          - some_folder

    name: assets/${{ matrix.path }}/
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/artifact-upload
        with:
          name: ${{ matrix.path }}
          path: assets/${{ matrix.path }}/

      - name: rm ./assets/${{ matrix.path }}
        run: rm -rf ./assets/${{ matrix.path }}

      - uses: ./.github/actions/artifact-download
        with:
          name: ${{ matrix.path }}
          path: downloaded/${{ matrix.path }}/
