name: Test actions/ssh-agent
on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

env:
  # auto-select LTS version
  NODE_VERSION: ""

jobs:
  ssh-private-key:
    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        submodules:
          - "true"
          - "false"
        OS:
          - ubuntu-latest
          - macos-latest
          # - windows-latest # FIXME not working: "Host key verification failed."
    runs-on: ${{ matrix.OS }}
    name: "w/ ssh-private-key @ ${{ matrix.OS }}"
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/ssh-agent
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # NOTE: We could use github-actions-node
      # But it has a dependency on github-actions-common
      - name: setup node @ ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      # NOTE: We could use github-actions-npm
      # But it has a dependency on github-actions-common
      - name: npm run setup:ci
        run: npm run setup:ci --if-present

      # Pulls from other repositories
      # Needs a personal access token with repo permissions
      - name: bower install
        run: npm run bower:install
      - name: ls bower_components
        run: ls ./bower_components
